upgraded lein

diff --git a/lein b/lein
--- a/lein
+++ b/lein
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-export LEIN_VERSION="1.4.2"
+export LEIN_VERSION="1.7.0"
 
 case $LEIN_VERSION in
     *SNAPSHOT) SNAPSHOT="YES" ;;
@@ -13,15 +13,16 @@ if [ "$OSTYPE" = "cygwin" ] && [ "$CLASSPATH" != "" ]; then
     CLASSPATH=`cygpath -up $CLASSPATH`
 fi
 
-if [ "$USER" = "root" ] && [ "$LEIN_ROOT" = "" ]; then
+if [ `whoami` = "root" ] && [ "$LEIN_ROOT" = "" ]; then
     echo "WARNING: You're currently running as root; probably by accident."
     echo "Press control-C to abort or Enter to continue as root."
     echo "Set LEIN_ROOT to disable this warning."
-    read
+    read _
 fi
 
+NOT_FOUND=1
 ORIGINAL_PWD="$PWD"
-while [ ! -r "$PWD/project.clj" ] && [ "$PWD" != "/" ] && [ ! $NOT_FOUND ]
+while [ ! -r "$PWD/project.clj" ] && [ "$PWD" != "/" ] && [ $NOT_FOUND -ne 0 ]
 do
     cd ..
     if [ "$(dirname "$PWD")" = "/" ]; then
@@ -31,15 +32,59 @@ do
 done
 
 if [ "$LEIN_HOME" = "" ]; then
-    LEIN_HOME="$HOME/.lein"
+  if [ -d "$PWD/.lein" ] && [ "$PWD" != "$HOME" ]; then
+    echo "Leiningen is running in bundled mode."
+    export LEIN_HOME="$PWD/.lein"
+  else
+    export LEIN_HOME="$HOME/.lein"
+  fi
 fi
 
-LEIN_PLUGINS="$(ls -1 lib/dev/*jar 2> /dev/null | tr \\n \:)"
-LEIN_USER_PLUGINS="$(ls -1 $LEIN_HOME/plugins/*jar 2> /dev/null | tr \\n \:)"
-CLASSPATH=$LEIN_USER_PLUGINS:$LEIN_PLUGINS:test/:src/:$CLASSPATH
-LEIN_JAR="$HOME/.lein/self-installs/leiningen-$LEIN_VERSION-standalone.jar"
-CLOJURE_JAR="$HOME/.m2/repository/org/clojure/clojure/1.2.0/clojure-1.2.0.jar"
+DEV_PLUGINS="$(ls -1 lib/dev/*jar .lein-plugins/*jar 2> /dev/null)"
+USER_PLUGINS="$(ls -1 "$LEIN_HOME"/plugins/*jar 2> /dev/null)"
+
+artifact_name () {
+    which rev > /dev/null
+    if [ $? -eq 0 ]; then
+        echo "$1" | sed -e "s/.*\/\(.*\)/\1/" | \
+            rev | sed -e "s/raj[-[:digit:].]*-\(.*\)/\1/" | rev
+    else
+        echo "$1"
+    fi
+}
+
+unique_user_plugins () {
+    saveIFS="$IFS"
+    IFS="$(printf '\n\t')"
+
+    plugins="$(echo "$DEV_PLUGINS"; echo "$USER_PLUGINS")"
+    artifacts="$(for i in $plugins; do echo "$(artifact_name "$i")"; done)"
+    duplicates="$(echo "$artifacts" | sort | uniq -d)"
+
+    if [ -z "$duplicates" ]; then
+        echo "$USER_PLUGINS"
+    else
+        for i in $USER_PLUGINS; do
+            artifact="$(artifact_name "$i")"
+            if ! echo "$duplicates" | grep -xq "$artifact"; then
+                echo "$i"
+            fi
+        done
+    fi
+    IFS="$saveIFS"
+}
+
+LEIN_PLUGIN_PATH="$(echo "$DEV_PLUGINS" | tr \\n :)"
+LEIN_USER_PLUGIN_PATH="$(echo "$(unique_user_plugins)" | tr \\n :)"
+CLASSPATH="$CLASSPATH:$LEIN_PLUGIN_PATH:$LEIN_USER_PLUGIN_PATH:test/:src/:resources/"
+LEIN_JAR="$LEIN_HOME/self-installs/leiningen-$LEIN_VERSION-standalone.jar"
+CLOJURE_JAR="$HOME/.m2/repository/org/clojure/clojure/1.2.1/clojure-1.2.1.jar"
 NULL_DEVICE=/dev/null
+
+# apply context specific CLASSPATH entries
+if [ -f .lein-classpath ]; then
+    CLASSPATH="`cat .lein-classpath`:$CLASSPATH"
+fi
 
 # normalize $0 on certain BSDs
 if [ "$(dirname "$0")" = "." ]; then
@@ -64,8 +109,8 @@ BIN_DIR="$(dirname "$SCRIPT")"
 if [ -r "$BIN_DIR/../src/leiningen/core.clj" ]; then
     # Running from source checkout
     LEIN_DIR="$(dirname "$BIN_DIR")"
-    LEIN_LIBS="$(find -H $LEIN_DIR/lib -mindepth 2> /dev/null 1 -maxdepth 1 -print0 | tr \\0 \:)"
-    CLASSPATH="$LEIN_LIBS:$CLASSPATH:$LEIN_DIR/src:$LEIN_DIR/resources:$LEIN_JAR"
+    LEIN_LIBS="$(find -H "$LEIN_DIR/lib" -mindepth 1 -maxdepth 1 -print0 2> /dev/null | tr \\0 \:)"
+    CLASSPATH="$CLASSPATH:$LEIN_LIBS:$LEIN_DIR/src:$LEIN_DIR/classes:$LEIN_DIR/resources:$LEIN_JAR"
 
     if [ "$LEIN_LIBS" = "" -a "$1" != "self-install" -a ! -r "$LEIN_JAR" ]; then
         echo "Leiningen is missing its dependencies. Please see \"Building\" in the README."
@@ -73,7 +118,7 @@ if [ -r "$BIN_DIR/../src/leiningen/core.clj" ]; then
     fi
 else
     # Not running from a checkout
-    CLASSPATH="$LEIN_JAR:$CLASSPATH"
+    CLASSPATH="$CLASSPATH:$LEIN_JAR"
 
     if [ ! -r "$LEIN_JAR" -a "$1" != "self-install" ]; then
         "$0" self-install
@@ -82,17 +127,41 @@ fi
 
 HTTP_CLIENT="wget --no-check-certificate -O"
 if type -p curl >/dev/null 2>&1; then
-    HTTP_CLIENT="curl --insecure -f -L -o"
+    if [ "$https_proxy" != "" ]; then
+        CURL_PROXY="-x $https_proxy"
+    fi
+    HTTP_CLIENT="curl $CURL_PROXY --insecure -f -L -o"
 fi
 
-JAVA_CMD=${JAVA_CMD:-"java"}
+# If we don't have Leiningen's own Clojure on the bootclasspath, boot
+# will be slower, and versions of Clojure in :dev-dependencies can
+# take precedence.
+if [ ! -r "$CLOJURE_JAR" ]; then
+    CLOJURE_JAR_URL=http://build.clojure.org/releases/org/clojure/clojure/1.2.1/clojure-1.2.1.jar
+    CLOJURE_HASH="be088d20c078ce48d42afba05984f1ef7c02142b"
+    mkdir -p "$(dirname $CLOJURE_JAR)"
+    $HTTP_CLIENT $CLOJURE_JAR $CLOJURE_JAR_URL
+    if [ "`shasum -a 1 $CLOJURE_JAR | cut -f 1 -d \" \"`" != "$CLOJURE_HASH" ]; then
+        echo "WARNING: Clojure jar failed to download from $CLOJURE_JAR_URL"
+    fi
+fi
+
+export JAVA_CMD=${JAVA_CMD:-"java"}
+export LEIN_JAVA_CMD=${LEIN_JAVA_CMD:-$JAVA_CMD}
 
 # Support $JAVA_OPTS for backwards-compatibility.
-JVM_OPTS=${JVM_OPTS:-$JAVA_OPTS}
+export JVM_OPTS="${JVM_OPTS:-"$JAVA_OPTS"}"
+export LEIN_JVM_OPTS=${LEIN_JVM_OPTS:-$JVM_OPTS}
 
+# TODO: investigate http://skife.org/java/unix/2011/06/20/really_executable_jars.html
 # If you're packaging this for a package manager (.deb, homebrew, etc)
 # you need to remove the self-install and upgrade functionality.
 if [ "$1" = "self-install" ]; then
+    if [ -r "$LEIN_JAR" ]; then
+      echo "The self-install jar already exists at $LEIN_JAR."
+      echo "If you wish to re-download, delete it and rerun \"$0 self-install\"."
+      exit 1
+    fi
     echo "Downloading Leiningen now..."
     LEIN_DIR=`dirname "$LEIN_JAR"`
     mkdir -p "$LEIN_DIR"
@@ -101,12 +170,18 @@ if [ "$1" = "self-install" ]; then
     if [ $? != 0 ]; then
         echo "Failed to download $LEIN_URL"
         if [ $SNAPSHOT = "YES" ]; then
-            echo "See README.md for SNAPSHOT build instructions."
+            echo "If you have Maven installed, you can do"
+            echo "mvn dependency:copy-dependencies; mv target/dependency lib"
+            echo "See README.md for further SNAPSHOT build instructions."
         fi
         rm $LEIN_JAR 2> /dev/null
         exit 1
     fi
 elif [ "$1" = "upgrade" ]; then
+    if [ "$LEIN_DIR" != "" ]; then
+        echo "The upgrade task is not meant to be run from a checkout."
+        exit 1
+    fi
     if [ $SNAPSHOT = "YES" ]; then
         echo "The upgrade task is only meant for stable releases."
         echo "See the \"Hacking\" section of the README."
@@ -123,10 +198,12 @@ elif [ "$1" = "upgrade" ]; then
             y|Y|"")
                 echo
                 echo "Upgrading..."
+                TARGET="/tmp/lein-$$-upgrade"
                 LEIN_SCRIPT_URL="https://github.com/technomancy/leiningen/raw/stable/bin/lein"
-                $HTTP_CLIENT "$SCRIPT" "$LEIN_SCRIPT_URL" \
+                $HTTP_CLIENT "$TARGET" "$LEIN_SCRIPT_URL" \
+                    && mv "$TARGET" "$SCRIPT" \
                     && chmod +x "$SCRIPT" \
-                    && echo && $SCRIPT self-install && echo && echo "Now running" `$SCRIPT version`
+                    && echo && "$SCRIPT" self-install && echo && echo "Now running" `$SCRIPT version`
                 exit $?;;
             *)
                 echo "Aborted."
@@ -148,28 +225,67 @@ else
     fi
 
     JLINE=""
-    if ([ "$1" = "repl" ] || [ "$1" = "interactive" ] || [ "$1" = "int" ]) &&
-        [ -z $INSIDE_EMACS ] && [ "$TERM" != "dumb" ]; then
+    if [ -z $INSIDE_EMACS ] && [ "$TERM" != "dumb" ]; then
         # Use rlwrap if it's available, otherwise fall back to JLine
         RLWRAP=`which rlwrap`
         if [ ! -x "$RLWRAP" ] || [ "$RLWRAP" = "" ]; then
+            if [ ! -r "$LEIN_HOME/.jline-warn" ]; then
+                echo "Using JLine for console I/O; install rlwrap for optimum experience."
+                touch "$LEIN_HOME/.jline-warn"
+            fi
             RLWRAP=""
             JLINE=jline.ConsoleRunner
             if [ "$OSTYPE" = "cygwin" ]; then
                 JLINE="-Djline.terminal=jline.UnixTerminal jline.ConsoleRunner"
                 CYGWIN_JLINE=y
             fi
+        else
+            # Test to see if rlwrap supports custom quote chars
+            rlwrap -m -q '"' echo "hi" > /dev/null 2>&1
+            if [ $? -eq 0 ]; then
+                RLWRAP="$RLWRAP -r -m -q '\"'"
+            fi
+            # see if there is a clojure-completion-file
+            RLWRAP_CLJ_WORDS_FILE=${RLWRAP_CLJ_WORDS_FILE:-"${HOME}/.clj_completions"}
+            RLWRAP_CLJ_WORDS_OPTION=""
+            if [ -r "${RLWRAP_CLJ_WORDS_FILE}" ]; then
+                RLWRAP_CLJ_WORDS_OPTION="-f ${RLWRAP_CLJ_WORDS_FILE}";
+            fi
+            RLWRAP="${RLWRAP} $RLWRAP_OPTIONS -b \"(){}[],^%$#@\";:'\" ${RLWRAP_CLJ_WORDS_OPTION}"
         fi
+    fi
+
+    test $CYGWIN_JLINE && stty -icanon min 1 -echo
+
+    TRAMPOLINE_FILE="/tmp/lein-trampoline-$$"
+    if [ "$OSTYPE" = "cygwin" ]; then
+        TRAMPOLINE_FILE=`cygpath -w $TRAMPOLINE_FILE`
     fi
 
     # The -Xbootclasspath argument is optional here: if the jar
     # doesn't exist everything will still work, it will just have a
     # slower JVM boot.
-    # TODO: add more to the boot classpath
-    test $CYGWIN_JLINE && stty -icanon min 1 -echo
-    exec $RLWRAP $JAVA_CMD -Xbootclasspath/a:"$CLOJURE_JAR" -client $JVM_OPTS \
+
+    ## TODO: -XX:+UseCompressedOops only works on 64 bit jvm
+    # is there some way of detecting 64bit at this stage? - tavisrudd
+    $RLWRAP $LEIN_JAVA_CMD \
+        -Xbootclasspath/a:"$CLOJURE_JAR" \
+        -client $LEIN_JVM_OPTS \
+        -XX:+TieredCompilation \
         -Dleiningen.original.pwd="$ORIGINAL_PWD" \
-        -cp "$CLASSPATH" $JLINE clojure.main -e "(use 'leiningen.core)(-main)" \
-        $NULL_DEVICE $@
-    test $CYGWIN_JLINE && stty icanon echo
+        -Dleiningen.trampoline-file=$TRAMPOLINE_FILE \
+        -cp "$CLASSPATH" \
+        $JLINE clojure.main \
+        -e "(use 'leiningen.core)(-main)" \
+        $NULL_DEVICE "$@"
+    EXIT_CODE=$?
+
+    if [ -r $TRAMPOLINE_FILE ]; then
+        TRAMPOLINE="$(cat $TRAMPOLINE_FILE)"
+        rm $TRAMPOLINE_FILE
+        exec sh -c "exec $TRAMPOLINE"
+    else
+        test $CYGWIN_JLINE && stty icanon echo
+        exit $EXIT_CODE
+    fi
 fi
